/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.eam.vista.Cliente;

import com.eam.controlador.CtlCarga;
import com.eam.controlador.CtlPuerto;
import com.eam.controlador.Main;
import com.eam.modelo.Cliente;
import com.eam.modelo.Puertos;
import com.eam.vista.FrmPrincipal;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;

/**
 *
 * @author Cristian
 */
public class FrmCliente extends javax.swing.JDialog {

    /**
     * Creates new form FrmCliente
     */
    String correo;
    CtlPuerto ctlpuerto;
    CtlCarga controCarga;

    public FrmCliente(java.awt.Frame parent, boolean modal, String correo) {

        super(parent, modal);
        this.correo = correo;
        ctlpuerto = new CtlPuerto();
        controCarga = new CtlCarga();
        initComponents();
        ListarRetorno();
    }

    public void ListarRetorno() {
        cbPuertoDescarga.setModel(ctlpuerto.listarPuertos("DESCARGA"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTamano_Cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPeso_Cliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbPuertoDescarga = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistNotificacion_Cliente = new javax.swing.JList<>();
        btnEnviarSolicitud_Cliente = new javax.swing.JButton();
        Notificaciones = new javax.swing.JLabel();
        btnCerrarSession_Cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cliente");

        jLabel2.setText("Tamaño:");

        txtTamano_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTamano_ClienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Peso:");

        txtPeso_Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPeso_ClienteKeyTyped(evt);
            }
        });

        jLabel4.setText("Puerto descarga:");

        jScrollPane1.setViewportView(jlistNotificacion_Cliente);

        btnEnviarSolicitud_Cliente.setText("Enviar Solicitud");
        btnEnviarSolicitud_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarSolicitud_ClienteActionPerformed(evt);
            }
        });

        Notificaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Notificaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Notificaciones.setText("Notificaciones");

        btnCerrarSession_Cliente.setText("Cerrar Session");
        btnCerrarSession_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSession_ClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTamano_Cliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPuertoDescarga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPeso_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1)
                    .addComponent(Notificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnEnviarSolicitud_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCerrarSession_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTamano_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPeso_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbPuertoDescarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(Notificaciones)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarSolicitud_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSession_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarSolicitud_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarSolicitud_ClienteActionPerformed
        try{
           String tamano = txtTamano_Cliente.getText();
        String peso = txtPeso_Cliente.getText();
        String estado = "ACTIVO";
        Puertos puerto = ctlpuerto.traerPuerto(Integer.parseInt((cbPuertoDescarga.getSelectedItem() + "").split(" - ")[0]));
        Cliente cliente = traerCliente();
        if(tamano.isEmpty() || peso.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos");
        }else{
           if(controCarga.crearCarga(new BigDecimal(tamano),new BigDecimal(peso), estado, cliente, puerto)){
         JOptionPane.showMessageDialog(this,"Se ha registrado con exito");
            }else{
            JOptionPane.showMessageDialog(this, "Hubo error al registrar");
             } 
            }  
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Datos erroneos");
        }
         
    }//GEN-LAST:event_btnEnviarSolicitud_ClienteActionPerformed

    private void btnCerrarSession_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSession_ClienteActionPerformed
        this.dispose();
        FrmPrincipal frmprincipal = new FrmPrincipal();
        frmprincipal.setLocationRelativeTo(null);
        frmprincipal.setVisible(true);
    }//GEN-LAST:event_btnCerrarSession_ClienteActionPerformed

    private void txtTamano_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTamano_ClienteKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTamano_ClienteKeyTyped

    private void txtPeso_ClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPeso_ClienteKeyTyped
       char c = evt.getKeyChar();
        if (!(Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPeso_ClienteKeyTyped

    public Cliente traerCliente() {
        ArrayList<String> campos = new ArrayList<>(), valores = new ArrayList<>();
        campos.add("usuariocorreo.correo");
        valores.add(correo);
        ArrayList<Cliente> cliente = new ArrayList(Main.dao.cargar("Cliente", campos, valores));
        return cliente.get(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Notificaciones;
    private javax.swing.JButton btnCerrarSession_Cliente;
    private javax.swing.JButton btnEnviarSolicitud_Cliente;
    private javax.swing.JComboBox<String> cbPuertoDescarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistNotificacion_Cliente;
    private javax.swing.JTextField txtPeso_Cliente;
    private javax.swing.JTextField txtTamano_Cliente;
    // End of variables declaration//GEN-END:variables
}
