-- MySQL Script generated by MySQL Workbench
-- Wed Apr 10 18:31:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Puertos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Puertos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Puertos` (
  `idPuertos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `coordenadasX` DECIMAL(11) NULL,
  `coordenadasY` DECIMAL(11) NULL,
  `tipoPuerto` VARCHAR(45) NULL,
  PRIMARY KEY (`idPuertos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ruta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ruta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ruta` (
  `idruta` INT NOT NULL AUTO_INCREMENT,
  `origen` VARCHAR(45) NULL,
  `destino` VARCHAR(45) NULL,
  `capacidadTotal` DECIMAL(11) NULL,
  `estado` VARCHAR(45) NULL,
  `fechaPartida` DATE NULL,
  PRIMARY KEY (`idruta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `cedula` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `Usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_Cliente_Usuario1_idx` (`Usuario_correo` ASC),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`Usuario_correo`)
    REFERENCES `mydb`.`Usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carga`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carga` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carga` (
  `idCarga` INT NOT NULL AUTO_INCREMENT,
  `tamanio` DECIMAL(11) NULL,
  `peso` DECIMAL(11) NULL,
  `estado` VARCHAR(45) NULL,
  `Puertos_idPuertos` INT NULL,
  `ruta_idruta` INT NULL,
  `Cliente_cedula` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarga`),
  INDEX `fk_Carga_Puertos_idx` (`Puertos_idPuertos` ASC),
  INDEX `fk_Carga_ruta1_idx` (`ruta_idruta` ASC),
  INDEX `fk_Carga_Cliente1_idx` (`Cliente_cedula` ASC),
  CONSTRAINT `fk_Carga_Puertos`
    FOREIGN KEY (`Puertos_idPuertos`)
    REFERENCES `mydb`.`Puertos` (`idPuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carga_ruta1`
    FOREIGN KEY (`ruta_idruta`)
    REFERENCES `mydb`.`ruta` (`idruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carga_Cliente1`
    FOREIGN KEY (`Cliente_cedula`)
    REFERENCES `mydb`.`Cliente` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Itinerario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Itinerario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Itinerario` (
  `idItinerario` INT NOT NULL AUTO_INCREMENT,
  `costo` DECIMAL(11) NULL,
  `clima` VARCHAR(45) NULL,
  `tiempo` DECIMAL(11) NULL,
  `ruta_idruta` INT NOT NULL,
  PRIMARY KEY (`idItinerario`),
  INDEX `fk_Itinerario_ruta1_idx` (`ruta_idruta` ASC),
  CONSTRAINT `fk_Itinerario_ruta1`
    FOREIGN KEY (`ruta_idruta`)
    REFERENCES `mydb`.`ruta` (`idruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Etapa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Etapa` (
  `idEtapa` INT NOT NULL AUTO_INCREMENT,
  `numeroEtapa` DECIMAL(11) NULL,
  `descripcion` VARCHAR(45) NULL,
  `tarifa` DECIMAL(11) NULL,
  `Itinerario_idItinerario` INT NOT NULL,
  PRIMARY KEY (`idEtapa`),
  INDEX `fk_Etapa_Itinerario1_idx` (`Itinerario_idItinerario` ASC),
  CONSTRAINT `fk_Etapa_Itinerario1`
    FOREIGN KEY (`Itinerario_idItinerario`)
    REFERENCES `mydb`.`Itinerario` (`idItinerario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`viajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`viajes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`viajes` (
  `idviajes` INT NOT NULL AUTO_INCREMENT,
  `fechaPartida` DATE NULL,
  `fechaLlegada` DATE NULL,
  `puertoLlegada` INT NULL,
  `puertoSalida` INT NULL,
  `Etapa_idEtapa` INT NULL,
  PRIMARY KEY (`idviajes`),
  INDEX `fk_viajes_Puertos1_idx` (`puertoLlegada` ASC),
  INDEX `fk_viajes_Puertos2_idx` (`puertoSalida` ASC),
  INDEX `fk_viajes_Etapa1_idx` (`Etapa_idEtapa` ASC),
  CONSTRAINT `fk_viajes_Puertos1`
    FOREIGN KEY (`puertoLlegada`)
    REFERENCES `mydb`.`Puertos` (`idPuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajes_Puertos2`
    FOREIGN KEY (`puertoSalida`)
    REFERENCES `mydb`.`Puertos` (`idPuertos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viajes_Etapa1`
    FOREIGN KEY (`Etapa_idEtapa`)
    REFERENCES `mydb`.`Etapa` (`idEtapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mail` (
  `idMail` INT NOT NULL AUTO_INCREMENT,
  `notificacion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `Usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMail`),
  INDEX `fk_Mail_Usuario1_idx` (`Usuario_correo` ASC),
  CONSTRAINT `fk_Mail_Usuario1`
    FOREIGN KEY (`Usuario_correo`)
    REFERENCES `mydb`.`Usuario` (`correo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
